[package]
name = "elis-lib"
version = "0.0.1"
authors = ["jonlamb-gh <lamb.jon.io@gmail.com>"]

[dependencies]
chrono = { version = "0.4.6", features = ["serde"] }
dimensioned = "0.7.0"
steel-cent = "0.2.2"
